//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Provider.Resources
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrestoResources
    {

        public static System.Resources.ResourceManager resourceMan;

        public static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PrestoResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Provider.Resources.PrestoResources", typeof(PrestoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string txtLoginFoodNetwork
        {
            get
            {
                return ResourceManager.GetString("txtLoginFoodNetwork", resourceCulture);
            }
        }

        public static string txtLoginUnleash
        {
            get
            {
                return ResourceManager.GetString("txtLoginUnleash", resourceCulture);
            }
        }

        public static string txtLoginDesc
        {
            get
            {
                return ResourceManager.GetString("txtLoginDesc", resourceCulture);
            }
        }

        public static string txtUserSignUpPageTopMsg
        {
            get
            {
                return ResourceManager.GetString("txtUserSignUpPageTopMsg", resourceCulture);
            }
        }

        public static string txtUserSignUpPageBtmMsg
        {
            get
            {
                return ResourceManager.GetString("txtUserSignUpPageBtmMsg", resourceCulture);
            }
        }
    }
}
